.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "DOGEDC" "1" "July 2014" "" ""
.
.SH "NAME"
\fBdogedc\fR \-\- Doge Decimal Classification
.
.SH "SYNOPSIS"
.
.nf

dogedc [class number]
.
.fi
.
.SH "DESCRIPTION"
.
.TP
\fBdogedc\fR
Without an argument, dogedc selects a Dewey Decimal class at random & returns its doge\-speak class name\.
.
.TP
\fBdogedc [class number]\fR
Dogedc looks up the first provided class number & returns its doge\-speak class name\.
.
.TP
\fBdogedc [\-\-help|\-h|help|usage]\fR
Print brief usage information\.
.
.SH "LICENSE"
.
.nf

GPL version 3\.0 or later, at your discretion\. https://www\.gnu\.org/copyleft/gpl\.html
.
.fi
.
.SH "AUTHOR"
.
.nf

Eric Phetteplace | http://phette\.net | https://github\.com/phette23 | https://twitter\.com/phette23
.
.fi

